# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
linters:
  default: none
  exclusions:
    paths:
      - internal/sdkprovider
  enable:
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    errcheck:
        exclude-functions:
          - (io.ReadCloser).Close
